# Generated by Django 4.1.1 on 2022-09-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_fooditems_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='qty',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
